In [1]:
import pandas as pd

In [4]:
df=pd.DataFrame([[1,0],[2,1],[3,0],[10,0],[15,1]],columns=['Features','Target'])
df

Features  Target
0         1       0
1         2       1
2         3       0
3        10       0
4        15       1

In [5]:
x=df.iloc[:,:-1].values

In [6]:
y=df.iloc[:,-1].values

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [9]:
x_t=sc.fit_transform(x)
x_t

array([[-0.95967751],
       [-0.77512414],
       [-0.59057078],
       [ 0.7013028 ],
       [ 1.62406964]])

In [10]:
import tensorflow as tf

In [11]:
n_features=x_t.shape[1]
n_features

1

In [12]:
output_neuron=1

In [13]:
#Assigning weights and bias
weightage=tf.random.truncated_normal(shape=[n_features,output_neuron],dtype='double')
bias=tf.random.truncated_normal(shape=[output_neuron],dtype='double')

In [14]:
weightage

<tf.Tensor: id=5, shape=(1, 1), dtype=float64, numpy=array([[-0.82434397]])>

In [15]:
bias

<tf.Tensor: id=11, shape=(1,), dtype=float64, numpy=array([0.7843153])>

We will truncate as the weights and bias assingned should be of different values

In [16]:
x

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [15]], dtype=int64)

# Building the perceptron

In [17]:
def output_layer(x,weightage,bias):
    z=x@weightage+bias
    probability=tf.nn.sigmoid(z)  #nn=neural n/w 
    return probability,z

In [18]:
var=output_layer(x_t,weightage,bias)
var

(<tf.Tensor: id=15, shape=(5, 1), dtype=float64, numpy=
 array([[0.82855485],
        [0.80585276],
        [0.78093933],
        [0.55136826],
        [0.3648264 ]])>,
 <tf.Tensor: id=14, shape=(5, 1), dtype=float64, numpy=
 array([[ 1.57541967],
        [ 1.42328421],
        [ 1.27114876],
        [ 0.20620057],
        [-0.55447671]])>)

In [19]:
import numpy as np
print((1/(1 + np.exp(-var[1]))))   #Sigmoid fn calculation

#var[1] is z values,i.e,linear values

[[0.82855485]
 [0.80585276]
 [0.78093933]
 [0.55136826]
 [0.3648264 ]]


In [20]:
output_layer(sc.transform(np.array([[1],[2],[3],[10],[15]])),weightage,bias)

(<tf.Tensor: id=20, shape=(5, 1), dtype=float64, numpy=
 array([[0.82855485],
        [0.80585276],
        [0.78093933],
        [0.55136826],
        [0.3648264 ]])>,
 <tf.Tensor: id=19, shape=(5, 1), dtype=float64, numpy=
 array([[ 1.57541967],
        [ 1.42328421],
        [ 1.27114876],
        [ 0.20620057],
        [-0.55447671]])>)